name: ZAP-Test

on:
  push: 
    branches: [ master ]

jobs: 
  build: 
    runs-on: ubuntu-18.04
    steps: 
      - uses: actions/checkout@v2
      - name: Get working directory
        run: echo $(PWD)
      - name: Build Image
        run: docker build -t juice_shop:latest .
      - name: Run Docker Container
        run: docker run -d -p 3000:3000 juice_shop:latest
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          target: 'http://localhost:3000/'
